-- Auto-generated Durable Execution demo outputs
-- Generated by scripts/regenerate_durable_data.sh
-- DO NOT EDIT MANUALLY

DELETE FROM demo_outputs;

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    1,
    'Ping-Pong',
    'Two workflows exchange messages back and forth',
    '=== Demo 1: Ping-Pong ===
[Alice] PING #1
[Bob] Got PING #1 from Alice
[Bob] PONG #2
[Alice] Got PONG #2 from Bob
[Alice] PING #3
[Bob] Got PING #3 from Alice
[Bob] PONG #4
[Alice] Got PONG #4 from Bob
[Alice] PING #5
[Bob] Got PING #5 from Alice
[Bob] PONG #6
[Alice] Got PONG #6 from Bob
[Alice] PING #7
[Bob] Got PING #7 from Alice
[Bob] PONG #8
[Alice] Got PONG #8 from Bob
[Alice] PING #9
[Bob] Got PING #9 from Alice
[Bob] PONG #10
[Alice] Got PONG #10 from Bob
[Alice] PING #11
[Bob] Got PING #11 from Alice
[Bob] PONG #12
[Alice] Got PONG #12 from Bob
[Alice] PING #13
[Bob] Got PING #13 from Alice
[Bob] PONG #14
[Alice] Got PONG #14 from Bob
[Alice] PING #15
[Bob] Got PING #15 from Alice
[Bob] PONG #16
[Alice] Got PONG #16 from Bob
[Alice] PING #17
[Bob] Got PING #17 from Alice
[Bob] PONG #18
[Alice] Got PONG #18 from Bob
[Alice] PING #19
[Bob] Got PING #19 from Alice
[Bob] PONG #20
[Bob] Done
[Alice] Got PONG #20 from Bob
[Alice] Done
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    2,
    'Chat Session',
    '10 messages in a conversation',
    '=== Demo 2: Chat Session ===
[Chat sess-1] Starting from message 0
  [Alice]: Hello!
  [Bob]: How are you?
  [Charlie]: Good thanks!
  [Alice]: Working on project
  [Bob]: Cool!
  [Charlie]: What''s the plan?
  [Alice]: About 2 weeks
  [Bob]: Need help?
  [Charlie]: Will let you know
  [Alice]: Bye!
Result: Some(Completed(Out(10)))
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    3,
    'Remote Commands',
    'Execute commands remotely',
    '=== Demo 3: Remote Commands ===
  [Exec] ECHO(Hello) = Hello
  [Exec] UPPER(world) = WORLD
  [Exec] REVERSE(stressed) = desserts
  [Exec] LEN(testing) = 7
  [Exec] ADD(10,20,30) = 60
  [Exec] ECHO(Done) = Done
  [Exec] UPPER(loud) = LOUD
  [Exec] REVERSE(level) = level
  [Exec] LEN(abcdefghij) = 10
  [Exec] ADD(1,2,3,4) = 10
Results: Hello, WORLD, desserts, 7, 60, Done, LOUD, level, 10, 10
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    4,
    'Durable Counter',
    'Counter with durable operations',
    '=== Demo 4: Durable Counter ===
  0 + 10 = 10
  10 + 5 = 15
  15 * 2 = 30
  30 - 3 = 27
  27 + 7 = 34
  34 * 3 = 102
  102 - 10 = 92
  92 + 1 = 93
  93 -> 0
  0 + 100 = 100
Final value: 100
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    5,
    'Saga Pattern',
    'Multi-step transaction with compensation',
    '=== Demo 5: Saga Pattern ===
Scenario 1: Success
  ✓ Hotel booked
  ✓ Flight booked
  ✓ Car booked
  All bookings successful!
Scenario 2: Flight fails
  ✓ Hotel booked
  ✗ Flight failed - Compensating...
  ↩ Hotel cancelled
Scenario 3: Car fails
  ✓ Hotel booked
  ✓ Flight booked
  ✗ Car failed - Compensating...
  ↩ Flight cancelled
  ↩ Hotel cancelled
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    6,
    'Durable Timer',
    'Timed events that survive restarts',
    '=== Demo 6: Durable Timer ===
  Step 1: Slept 50ms (total: 57ms)
  Step 2: Slept 100ms (total: 164ms)
  Step 3: Slept 75ms (total: 245ms)
  Step 4: Slept 50ms (total: 300ms)
  Step 5: Slept 100ms (total: 405ms)
  Step 6: Slept 75ms (total: 484ms)
  Step 7: Slept 50ms (total: 538ms)
  Step 8: Slept 100ms (total: 643ms)
  Step 9: Slept 75ms (total: 721ms)
  Step 10: Slept 50ms (total: 776ms)
10 timed events completed
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    7,
    'State Machine',
    'Order processing state transitions',
    '=== Demo 7: Order State Machine ===
Order 1:
  [ORD-001] Items: Laptop, Mouse
  [ORD-001] Created -> Validated
  [ORD-001] Validated -> PaymentPending
  [ORD-001] PaymentPending -> Paid
  [ORD-001] Paid -> Preparing
  [ORD-001] Preparing -> Shipped
  [ORD-001] Shipped -> InTransit
  [ORD-001] InTransit -> Delivered
  Final: Delivered (7 transitions)
Order 2:
  [ORD-002] Items: Monitor
  [ORD-002] Created -> Validated
  [ORD-002] Validated -> PaymentPending
  [ORD-002] PaymentPending -> Paid
  [ORD-002] Paid -> Preparing
  [ORD-002] Preparing -> Shipped
  [ORD-002] Shipped -> InTransit
  [ORD-002] InTransit -> Delivered
  Final: Delivered (7 transitions)
Order 3:
  [ORD-003] Items: Keyboard, Webcam
  [ORD-003] Created -> Validated
  [ORD-003] Validated -> PaymentPending
  [ORD-003] PaymentPending -> Paid
  [ORD-003] Paid -> Preparing
  [ORD-003] Preparing -> Shipped
  [ORD-003] Shipped -> InTransit
  [ORD-003] InTransit -> Delivered
  Final: Delivered (7 transitions)
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    8,
    'Parallel Fan-Out',
    'Distribute tasks to workers',
    '=== Demo 8: Parallel Fan-Out ===
Distributing 10 tasks...
  [W1] Task 1: 10² = 100
  [W2] Task 2: 20² = 400
  [W3] Task 3: 30² = 900
  [W0] Task 4: 40² = 1600
  [W1] Task 5: 50² = 2500
  [W2] Task 6: 60² = 3600
  [W3] Task 7: 70² = 4900
  [W0] Task 8: 80² = 6400
  [W2] Task 10: 100² = 10000
  [W1] Task 9: 90² = 8100
Results: 100, 400, 900, 1600, 2500, 3600, 4900, 6400, 8100, 10000
Total time: 222ms
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    9,
    'Automatic Retry',
    'Retry on transient failures',
    '=== Demo 9: Automatic Retry ===
  Calling /ok (will fail 0 times)...
    [API] /ok attempt 1 SUCCESS
  Calling /fails-2x (will fail 2 times)...
    [API] /fails-2x attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-2x attempt 2 FAILED
    Retry in 100ms...
    [API] /fails-2x attempt 3 SUCCESS
  Calling /fails-3x (will fail 3 times)...
    [API] /fails-3x attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-3x attempt 2 FAILED
    Retry in 100ms...
    [API] /fails-3x attempt 3 FAILED
    Retry in 150ms...
    [API] /fails-3x attempt 4 SUCCESS
  Calling /always-fails (will fail 10 times)...
    [API] /always-fails attempt 1 FAILED
    Retry in 50ms...
    [API] /always-fails attempt 2 FAILED
    Retry in 100ms...
    [API] /always-fails attempt 3 FAILED
    Retry in 150ms...
    [API] /always-fails attempt 4 FAILED
    Retry in 200ms...
    [API] /always-fails attempt 5 FAILED
  Calling /ok-2 (will fail 0 times)...
    [API] /ok-2 attempt 1 SUCCESS
  Calling /fails-1x (will fail 1 times)...
    [API] /fails-1x attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-1x attempt 2 SUCCESS
  Calling /ok-3 (will fail 0 times)...
    [API] /ok-3 attempt 1 SUCCESS
  Calling /fails-2x-b (will fail 2 times)...
    [API] /fails-2x-b attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-2x-b attempt 2 FAILED
    Retry in 100ms...
    [API] /fails-2x-b attempt 3 SUCCESS
  Calling /ok-4 (will fail 0 times)...
    [API] /ok-4 attempt 1 SUCCESS
  Calling /fails-1x-b (will fail 1 times)...
    [API] /fails-1x-b attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-1x-b attempt 2 SUCCESS
--- Summary ---
  ✓ /ok: OK from /ok
  ✓ /fails-2x: OK from /fails-2x
  ✓ /fails-3x: OK from /fails-3x
  ✗ /always-fails: FAILED: Transient failure
  ✓ /ok-2: OK from /ok-2
  ✓ /fails-1x: OK from /fails-1x
  ✓ /ok-3: OK from /ok-3
  ✓ /fails-2x-b: OK from /fails-2x-b
  ✓ /ok-4: OK from /ok-4
  ✓ /fails-1x-b: OK from /fails-1x-b
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    10,
    'Checkpoint Recovery',
    'Resume from crash',
    '=== Demo 10: Checkpoint and Recovery ===
Phase 1: Run until crash at item 5
  [batch-001] Starting from item 0
  [batch-001] Processed batch-001-0
  [batch-001] Processed batch-001-1
  [batch-001] Processed batch-001-2
  [batch-001] *** CHECKPOINT at 3 ***
  [batch-001] Processed batch-001-3
  [batch-001] Processed batch-001-4
  [batch-001] !!! CRASH at item 5 !!!
Phase 2: Resume after ''restart'' (items 0-4 not reprocessed)
  [batch-001] Resuming from item 5
  [batch-001] *** CHECKPOINT at 6 ***
  [batch-001] *** CHECKPOINT at 9 ***
--- Verification ---
  Total unique items: 5 (expected: 10)
  No duplicates: false
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    11,
    'Multi-Node Cluster',
    'Cluster formation with SWIM gossip',
    '============================================================
Demo 11: Multi-Node Cluster Formation
============================================================
This demo shows 3 nodes forming a cluster using SWIM gossip.
Nodes discover each other automatically via seed nodes.
--- Phase 1: Starting Seed Node ---
Starting node-1 (seed node) on port 7800...
  ✓ node-1 started as seed
  ✓ node-1 sees 1 alive member(s)
--- Phase 2: Nodes Join via Seed ---
Starting node-2 on port 7801 (joining via seed at 7800)...
  ✓ node-2 joined cluster
Starting node-3 on port 7802 (joining via seed at 7800)...
  ✓ node-3 joined cluster
--- Phase 3: Cluster State ---
All nodes discover each other via gossip propagation:
  node-1 sees: node-3, node-2, node-1
  node-2 sees: node-3, node-2, node-1
  node-3 sees: node-3, node-2, node-1
Cluster statistics:
  node-1: 3 alive, 3 in hash ring
  node-2: 3 alive, 3 in hash ring
  node-3: 3 alive, 3 in hash ring
--- Phase 4: Workflow Routing Preview ---
Consistent hashing routes workflows to specific nodes:
  workflow-1 → node-1 (local to node-1)
  workflow-2 → node-2
  workflow-3 → node-2
  workflow-4 → node-2
  workflow-5 → node-1 (local to node-1)
  workflow-6 → node-2
--- Phase 5: Graceful Shutdown ---
Stopping all nodes...
  ✓ All nodes stopped
============================================================
Demo 11 Complete
============================================================'
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    12,
    'Distributed Execution',
    'Workflow routing via consistent hashing',
    '============================================================
Demo 12: Distributed Workflow Execution
============================================================
This demo shows workflows being routed to and executed on
specific nodes based on consistent hashing.
--- Setting Up 3-Node Cluster ---
Starting node-1 (seed)...
Starting node-2...
Starting node-3...
Cluster ready: 3 nodes
--- Submitting Workflows to Cluster ---
Each workflow ID is hashed to determine its owner node.
Workflows are executed locally on their assigned node.
Workflow routing based on consistent hashing:
  task-alpha → node-2 (square(5))
  task-beta → node-1 (double(7))
  task-gamma → node-1 (triple(3))
  task-delta → node-3 (square(4))
  task-epsilon → node-3 (double(10))
  task-zeta → node-2 (triple(6))
--- Workflow Distribution ---
Tasks distributed across nodes:
  node-1: ██░░░░ (2 tasks)
  node-2: ██░░░░ (2 tasks)
  node-3: ██░░░░ (2 tasks)
Note: Consistent hashing ensures workflows route to the same
      node every time, enabling local state and durability.
--- Cleanup ---
All nodes stopped.
============================================================
Demo 12 Complete
============================================================'
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    13,
    'Failure & Rebalancing',
    'Node failure detection and recovery',
    '============================================================
Demo 13: Node Failure and Rebalancing
============================================================
This demo shows what happens when a cluster node fails.
The remaining nodes detect the failure and rebalance work.
--- Phase 1: Cluster Formation ---
Starting 3-node cluster...
  ✓ Cluster ready: 3 nodes
--- Phase 2: Initial Workflow Routing ---
Initial workflow routing (all 3 nodes):
  workflow-1 → node-1
  workflow-2 → node-2
  workflow-3 → node-2
  workflow-4 → node-2
  workflow-5 → node-1
  workflow-6 → node-2
Distribution:
  node-1: 2 workflows
  node-2: 4 workflows
  node-3: 0 workflows
--- Phase 3: Simulating Node Failure ---
ALERT: node-2 has crashed!
  ✓ SWIM gossip would detect failure via ping timeouts
  ✓ Node marked as SUSPECT then DEAD after timeout
--- Phase 4: Routing After Failure ---
After node-2 failure, workflows are rerouted to surviving nodes:
  workflow-1 → node-1
  workflow-2 → node-3
  workflow-3 → node-3
  workflow-4 → node-3
  workflow-5 → node-1
  workflow-6 → node-3
New distribution (node-2 workflows redistributed):
  node-1: 2 workflows (was 2)
  node-2: DOWN
  node-3: 4 workflows (was 0)
--- Phase 5: Workflow Recovery Process ---
When a node fails, workflows owned by that node need recovery:
  1. Detect failure via SWIM gossip (ping timeout)
  2. Mark node as SUSPECT, then DEAD after confirmation
  3. Update hash ring to exclude dead node
  4. New owner node loads workflow state from durable storage
  5. Workflow resumes from last journaled checkpoint
With durable execution, NO WORK IS LOST - journals survive failures.
--- Phase 6: Adding Replacement Node ---
Starting node-4 as replacement...
  ✓ node-4 joined cluster
Cluster now has 2 nodes
Final routing with replacement node-4:
  workflow-1 → node-1
  workflow-2 → node-4
  workflow-3 → node-4
  workflow-4 → node-3
  workflow-5 → node-1
  workflow-6 → node-3
Distribution with node-4:
  node-1: 2 workflows
  node-3: 2 workflows
  node-4: 2 workflows (new)
--- Cleanup ---
All nodes stopped.
============================================================
Demo 13 Complete
============================================================'
);

