-- Auto-generated DSL demo outputs
-- Generated by scripts/regenerate_dsl_data.sh
-- DO NOT EDIT MANUALLY

DELETE FROM demo_outputs;

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    1,
    'Ping-Pong',
    'Two workflows exchange messages back and forth',
    '=== Demo 1: Ping-Pong ===
[Alice] PING #1
[Bob] Got PING #1 from Alice
[Bob] PONG #2
[Alice] Got PONG #2 from Bob
[Alice] PING #3
[Bob] Got PING #3 from Alice
[Bob] PONG #4
[Alice] Got PONG #4 from Bob
[Alice] PING #5
[Bob] Got PING #5 from Alice
[Bob] PONG #6
[Alice] Got PONG #6 from Bob
[Alice] PING #7
[Bob] Got PING #7 from Alice
[Bob] PONG #8
[Alice] Got PONG #8 from Bob
[Alice] PING #9
[Bob] Got PING #9 from Alice
[Bob] PONG #10
[Alice] Got PONG #10 from Bob
[Alice] PING #11
[Bob] Got PING #11 from Alice
[Bob] PONG #12
[Alice] Got PONG #12 from Bob
[Alice] PING #13
[Bob] Got PING #13 from Alice
[Bob] PONG #14
[Alice] Got PONG #14 from Bob
[Alice] PING #15
[Bob] Got PING #15 from Alice
[Bob] PONG #16
[Alice] Got PONG #16 from Bob
[Alice] PING #17
[Bob] Got PING #17 from Alice
[Bob] PONG #18
[Alice] Got PONG #18 from Bob
[Alice] PING #19
[Bob] Got PING #19 from Alice
[Bob] PONG #20
[Alice] Got PONG #20 from Bob
[Alice] Done
[Bob] Done
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    2,
    'Chat Session',
    '10 messages in a conversation',
    '=== Demo 2: Chat Session ===
[Chat sess-1] Starting from message 0
  [Alice]: Hello!
  [Bob]: How are you?
  [Charlie]: Good thanks!
  [Alice]: Working on project
  [Bob]: Cool!
  [Charlie]: What''s the plan?
  [Alice]: About 2 weeks
  [Bob]: Need help?
  [Charlie]: Will let you know
  [Alice]: Bye!
Result: Some(Completed(Out(10)))
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    3,
    'Remote Commands',
    'Execute commands remotely',
    '=== Demo 3: Remote Commands ===
  [Exec] ECHO(Hello) = Hello
  [Exec] UPPER(world) = WORLD
  [Exec] REVERSE(stressed) = desserts
  [Exec] LEN(testing) = 7
  [Exec] ADD(10,20,30) = 60
  [Exec] ECHO(Done) = Done
  [Exec] UPPER(loud) = LOUD
  [Exec] REVERSE(level) = level
  [Exec] LEN(abcdefghij) = 10
  [Exec] ADD(1,2,3,4) = 10
Results: Hello, WORLD, desserts, 7, 60, Done, LOUD, level, 10, 10
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    4,
    'Durable Counter',
    'Counter with durable operations',
    '=== Demo 4: Durable Counter ===
  0 + 10 = 10
  10 + 5 = 15
  15 * 2 = 30
  30 - 3 = 27
  27 + 7 = 34
  34 * 3 = 102
  102 - 10 = 92
  92 + 1 = 93
  93 -> 0
  0 + 100 = 100
Final value: 100
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    5,
    'Saga Pattern',
    'Multi-step transaction with compensation',
    '=== Demo 5: Saga Pattern ===
Scenario 1: Success
  ✓ Hotel booked
  ✓ Flight booked
  ✓ Car booked
  All bookings successful!
Scenario 2: Flight fails
  ✓ Hotel booked
  ✗ Flight failed - Compensating...
  ↩ Hotel cancelled
Scenario 3: Car fails
  ✓ Hotel booked
  ✓ Flight booked
  ✗ Car failed - Compensating...
  ↩ Flight cancelled
  ↩ Hotel cancelled
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    6,
    'Durable Timer',
    'Timed events that survive restarts',
    '=== Demo 6: Durable Timer ===
  Step 1: Slept 50ms (total: 57ms)
  Step 2: Slept 100ms (total: 164ms)
  Step 3: Slept 75ms (total: 245ms)
  Step 4: Slept 50ms (total: 302ms)
  Step 5: Slept 100ms (total: 407ms)
  Step 6: Slept 75ms (total: 485ms)
  Step 7: Slept 50ms (total: 541ms)
  Step 8: Slept 100ms (total: 647ms)
  Step 9: Slept 75ms (total: 726ms)
  Step 10: Slept 50ms (total: 781ms)
10 timed events completed
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    7,
    'State Machine',
    'Order processing state transitions',
    '=== Demo 7: Order State Machine ===
Order 1:
  [ORD-001] Items: Laptop, Mouse
  [ORD-001] Created -> Validated
  [ORD-001] Validated -> PaymentPending
  [ORD-001] PaymentPending -> Paid
  [ORD-001] Paid -> Preparing
  [ORD-001] Preparing -> Shipped
  [ORD-001] Shipped -> InTransit
  [ORD-001] InTransit -> Delivered
  Final: Delivered (7 transitions)
Order 2:
  [ORD-002] Items: Monitor
  [ORD-002] Created -> Validated
  [ORD-002] Validated -> PaymentPending
  [ORD-002] PaymentPending -> Paid
  [ORD-002] Paid -> Preparing
  [ORD-002] Preparing -> Shipped
  [ORD-002] Shipped -> InTransit
  [ORD-002] InTransit -> Delivered
  Final: Delivered (7 transitions)
Order 3:
  [ORD-003] Items: Keyboard, Webcam
  [ORD-003] Created -> Validated
  [ORD-003] Validated -> PaymentPending
  [ORD-003] PaymentPending -> Paid
  [ORD-003] Paid -> Preparing
  [ORD-003] Preparing -> Shipped
  [ORD-003] Shipped -> InTransit
  [ORD-003] InTransit -> Delivered
  Final: Delivered (7 transitions)
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    8,
    'Parallel Fan-Out',
    'Distribute tasks to workers',
    '=== Demo 8: Parallel Fan-Out ===
Distributing 10 tasks...
  [W1] Task 1: 10² = 100
  [W2] Task 2: 20² = 400
  [W3] Task 3: 30² = 900
  [W0] Task 4: 40² = 1600
  [W1] Task 5: 50² = 2500
  [W2] Task 6: 60² = 3600
  [W3] Task 7: 70² = 4900
  [W0] Task 8: 80² = 6400
  [W2] Task 10: 100² = 10000
  [W1] Task 9: 90² = 8100
Results: 100, 400, 900, 1600, 2500, 3600, 4900, 6400, 8100, 10000
Total time: 224ms
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    9,
    'Automatic Retry',
    'Retry on transient failures',
    '=== Demo 9: Automatic Retry ===
  Calling /ok (will fail 0 times)...
    [API] /ok attempt 1 SUCCESS
  Calling /fails-2x (will fail 2 times)...
    [API] /fails-2x attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-2x attempt 2 FAILED
    Retry in 100ms...
    [API] /fails-2x attempt 3 SUCCESS
  Calling /fails-3x (will fail 3 times)...
    [API] /fails-3x attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-3x attempt 2 FAILED
    Retry in 100ms...
    [API] /fails-3x attempt 3 FAILED
    Retry in 150ms...
    [API] /fails-3x attempt 4 SUCCESS
  Calling /always-fails (will fail 10 times)...
    [API] /always-fails attempt 1 FAILED
    Retry in 50ms...
    [API] /always-fails attempt 2 FAILED
    Retry in 100ms...
    [API] /always-fails attempt 3 FAILED
    Retry in 150ms...
    [API] /always-fails attempt 4 FAILED
    Retry in 200ms...
    [API] /always-fails attempt 5 FAILED
  Calling /ok-2 (will fail 0 times)...
    [API] /ok-2 attempt 1 SUCCESS
  Calling /fails-1x (will fail 1 times)...
    [API] /fails-1x attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-1x attempt 2 SUCCESS
  Calling /ok-3 (will fail 0 times)...
    [API] /ok-3 attempt 1 SUCCESS
  Calling /fails-2x-b (will fail 2 times)...
    [API] /fails-2x-b attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-2x-b attempt 2 FAILED
    Retry in 100ms...
    [API] /fails-2x-b attempt 3 SUCCESS
  Calling /ok-4 (will fail 0 times)...
    [API] /ok-4 attempt 1 SUCCESS
  Calling /fails-1x-b (will fail 1 times)...
    [API] /fails-1x-b attempt 1 FAILED
    Retry in 50ms...
    [API] /fails-1x-b attempt 2 SUCCESS
--- Summary ---
  ✓ /ok: OK from /ok
  ✓ /fails-2x: OK from /fails-2x
  ✓ /fails-3x: OK from /fails-3x
  ✗ /always-fails: FAILED: Transient failure
  ✓ /ok-2: OK from /ok-2
  ✓ /fails-1x: OK from /fails-1x
  ✓ /ok-3: OK from /ok-3
  ✓ /fails-2x-b: OK from /fails-2x-b
  ✓ /ok-4: OK from /ok-4
  ✓ /fails-1x-b: OK from /fails-1x-b
=== Complete ==='
);

INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    10,
    'Checkpoint Recovery',
    'Resume from crash',
    '=== Demo 10: Checkpoint and Recovery ===
Phase 1: Run until crash at item 5
  [batch-001] Starting from item 0
  [batch-001] Processed batch-001-0
  [batch-001] Processed batch-001-1
  [batch-001] Processed batch-001-2
  [batch-001] *** CHECKPOINT at 3 ***
  [batch-001] Processed batch-001-3
  [batch-001] Processed batch-001-4
  [batch-001] !!! CRASH at item 5 !!!
Phase 2: Resume after ''restart'' (items 0-4 not reprocessed)
  [batch-001] Resuming from item 5
  [batch-001] *** CHECKPOINT at 6 ***
  [batch-001] *** CHECKPOINT at 9 ***
--- Verification ---
  Total unique items: 5 (expected: 10)
  No duplicates: false
=== Complete ==='
);

