#!/bin/bash
# Regenerate DSL demo outputs
# Runs all 10 demos and captures their output to docs/dsl/seed_data.sql

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$PROJECT_ROOT/docs/dsl/seed_data.sql"

echo "════════════════════════════════════════════════════════════"
echo "  Regenerating DSL Demo Outputs"
echo "════════════════════════════════════════════════════════════"
echo ""

cd "$PROJECT_ROOT"

# Start the SQL file
cat > "$OUTPUT_FILE" << 'HEADER'
-- Auto-generated DSL demo outputs
-- Generated by scripts/regenerate_dsl_data.sh
-- DO NOT EDIT MANUALLY

DELETE FROM demo_outputs;

HEADER

# Function to capture demo output and append to SQL
capture_demo() {
    local num=$1
    local title=$2
    local desc=$3
    local class=$4

    echo "Running Demo $num: $title..."

    # Run the demo and capture output, filtering sbt noise
    local output
    output=$(sbt "runMain kraft.demos.$class" 2>&1 | \
        sed -n 's/^\[info\] //p' | \
        grep -v "^welcome\|^loading\|^set current\|^compiling\|^done compiling\|^running (fork)\|^SLF4J\|^WARNING\|^\[success\]" || true)

    # Escape single quotes for SQL
    local escaped_output
    escaped_output=$(echo "$output" | sed "s/'/''/g")

    # Append INSERT statement
    cat >> "$OUTPUT_FILE" << INSERTEOF
INSERT INTO demo_outputs (demo_number, title, description, output) VALUES (
    $num,
    '$title',
    '$desc',
    '$escaped_output'
);

INSERTEOF

    local lines
    lines=$(echo "$output" | wc -l | tr -d ' ')
    echo "  Captured $lines lines"
}

# Run all 10 demos
capture_demo 1 "Ping-Pong" "Two workflows exchange messages back and forth" "Demo01"
capture_demo 2 "Chat Session" "10 messages in a conversation" "Demo02"
capture_demo 3 "Remote Commands" "Execute commands remotely" "Demo03"
capture_demo 4 "Durable Counter" "Counter with durable operations" "Demo04"
capture_demo 5 "Saga Pattern" "Multi-step transaction with compensation" "Demo05"
capture_demo 6 "Durable Timer" "Timed events that survive restarts" "Demo06"
capture_demo 7 "State Machine" "Order processing state transitions" "Demo07"
capture_demo 8 "Parallel Fan-Out" "Distribute tasks to workers" "Demo08"
capture_demo 9 "Automatic Retry" "Retry on transient failures" "Demo09"
capture_demo 10 "Checkpoint Recovery" "Resume from crash" "Demo10"
capture_demo 11 "Cluster Operations" "Seed nodes, gossip, and consistent hashing" "Demo11"

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Demo outputs saved to: $OUTPUT_FILE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "To regenerate the book HTML, run: make docs-render"
